### ISSUE TITLE
overlays support

### ISSUE THREAD

**Issue by domenkozar** [domenkozar/hie-nix#1]
@mpickering requested overlays support in https://twitter.com/mpickering_/status/959721290419593217

**Comment by pjan** [comment]
Would love this as well.

Use cases:
1) I'm managing my environment with `nix-darwin`. If this exists as an overlay, I can just set it there as one of the systemPackages to be installed.
2) As an overlay, it's easier to just set it as one of the additional dependencies when launching a `nix-shell`

**Comment by mpickering** [comment]
It is somewhat trivial to use in an overlay. You can just clone the repo locally (or fetch it from another source) and then add the following to an overlay.

```
haskell-ide = (import ./hie-nix/default.nix).hies;
```

**Comment by jhenahan** [comment]
For the `nix-darwin` case, I created an overlay at `~/.config/nixpkgs/overlays/hie-overlay.nix`:

```
self: super:

{
  haskell-ide = (import ~/hie-nix/default.nix).hies;
}
```

Then added

```
nix.nixPath = [
  <other paths here>
  "hie-overlay=$HOME/.config/nixpkgs/overlays/hie-overlay.nix"
  ];

nixpkgs.overlays = [ (import <hie-overlay>) ];
```

to my `~/.nixpkgs/darwin-configuration.nix`. I'm not sure if all that's necessary, but it seemed to work for making Nix aware of it. The build failed due to trying to pull in a broken version of Libsystem, but hey, progress!

**Comment by michalrus** [comment]
Or something like https://github.com/michalrus/dotfiles/blob/3a827a3cdb1cb4df39579ffefc550492666ccac0/nixos-config/overlays/pkgs/haskell-ide-engine.nix#L14-L16 … to prevent GC.

**Comment by domenkozar** [comment]
Let me know if this is still needed with #17, but I'm closing is in favor.

**Comment by asymmetric** [comment]
I had to to `(import ~/path/to/hies/default.nix {}).hies`, not sure if this has changed in recent `nix` versions. Otherwise I was getting a `error: value is a function while a set was expected`.
