### ISSUE TITLE
Can't install by following instructions

### ISSUE THREAD

**Issue by razvan-panda** [domenkozar/hie-nix#2]
I tried both:

    nix-env -f hie-nix -iA hies
    nix-env -f hie-nix -iA hie82

and they print the error:

> error: getting information about ‘/home/neo/Sources/hie-nix/hie-nix’: No such file or directory

There does not seem to be any hie-nix file in the repository so I don't understand how it could have worked.

I tried running `update.sh` and then run the commands again but got same errors.

**Comment by razvan-panda** [comment]
I got hie80 installed using: `nix-env -f default.nix -iA hie80`

**Comment by razvan-panda** [comment]
And hie82 installed via: `nix-env -f default.nix -iA hie82` also works.

But trying to install with hies does not work:

    [neo@nixos:~/Sources/hie-nix]$ nix-env -f default.nix -iA hies
    installing ‘hies’
    error: undefined variable ‘hie80’ at /home/neo/Sources/hie-nix/default.nix:21:12
    (use ‘--show-trace’ to show detailed location information)

**Comment by razvan-panda** [comment]
When should `./update.sh` be run and what does it do?

**Comment by razvan-panda** [comment]
About `nix-env -f hie-nix -iA hie82` it didn't work because I `cd`ed into the folder without realizing I should not do that for it to work.

The command with installing `hies` is still erroring out like above though.

**Comment by domenkozar** [comment]
Thanks! Fixed.
