### ISSUE TITLE
Is there a way to always alias the executable to hie?

### ISSUE THREAD

**Issue by wpoosanguansit** [domenkozar/hie-nix#3]
I would like to fix the alias for other tools to call hie.  Is there a way to configure that?  Also related to the installation, I am installing hie package by specifying hie in a config file like:

hie = import ./hie-nix;

and run that by putting hie in:

haskellEnv = with pkgs; buildEnv {
            name = "baseEnv";
            paths = [
                hie
            ]
}

nix-env -iA nixpkgs.haskellEnv

However, I still need to run the following install to get hie-8.2 in the path

~/.nixpkgs/ nix-env -f hie-nix -iA hies

The question is how do I pass in the flag -f or how do I have hie-8.2 or the alias right after the config install?  Appreciate your help.

**Comment by domenkozar** [comment]
If you want just hie82 do `nix-env -f hie-nix -iA hie82` and it should install `hie` executable. 

`hies` is mean for use with hie-wrapper.

**Comment by wpoosanguansit** [comment]
Thanks for your help.
