### ISSUE TITLE
Update to latest hie?

### ISSUE THREAD

**Issue by o1lo01ol1o** [domenkozar/hie-nix#31]
Hi, 
  Thanks for this package, it's quite helpful in my nix-haskell dev world.  The latest master of the `haskell-ide-engine` added support for cabal new-* projects.  Would it be possible to update the ghc8.*.nix expressions to build from current master?  

I'd do it myself but I can't get the stack2nix tool to work correctly . :-\

**Comment by domenkozar** [comment]
I was just meaining to: #32
