### ISSUE TITLE
stack requires nix: enable: true

### ISSUE THREAD

**Issue by bbarker** [domenkozar/hie-nix#42]
Ideally, the wrapper could be able to inject `--nix` into all stack commands. I try not to have `nix: enable: true` in my stack.yaml since this seems to break the build for non-nix users.

**Comment by fendor** [comment]
You should not have `nix: enable: true` in `<your-project>/stack.yaml` but rather in `~/.stack/global-project/stack.yaml`
There it does not break the build for non-nix-users.

**Comment by bbarker** [comment]
@fendor That sounds like an excellent suggestion, and I didn't now about it. However, when I tried that and did e.g. `stack test` instead of `stack --nix test` on one particular project, I received many odd build errors about missing files in cabal builds.

**Comment by fendor** [comment]
Did you try running `stack clean`? Also, do you have system library dependencies, such as `zlib`? These still have to be added to `<your-project>/stack.yaml`.
You can also try to share your project, so that we can take a look on it.

**Comment by bbarker** [comment]
@fendor woops, I had totally missed that :-( Seems to work for me!
