### ISSUE TITLE
Endless looping without cachix

### ISSUE THREAD

**Issue by janat08** [domenkozar/hie-nix#44]
For those that just scan for CLI commands and enter them without further adieu, it would be helpful if ``nix-env -iA hies -f https://github.com/domenkozar/hie-nix/tarball/master`` wouldn't loop endlessly.

**Comment by domenkozar** [comment]
How does it loop? Can you attach logging?

**Comment by janat08** [comment]
I got rid of it. I'm running effectively ubuntu 18.04

**Comment by domenkozar** [comment]
How did you get rid of it?

**Comment by domenkozar** [comment]
I'm closing this as there doesn't seem to be a way to reproduce, so I won't be able to fix it anyway. Please reopen with logs or some other extra information
