### ISSUE TITLE
Merging hie-nix into nixpkgs

### ISSUE THREAD

**Issue by ar1a** [domenkozar/hie-nix#50]
Hi! What's stopping us from merging hie-nix into nixpkgs? It would be awful nice to not have to use cachix.

**Comment by domenkozar** [comment]
Duplicates https://github.com/domenkozar/hie-nix/issues/23#issuecomment-418647970

**Comment by ar1a** [comment]
Totally forgot i commented on that. Must have been why it was on my mind!
