### ISSUE TITLE
Error building yaml-0.8.32 when not hitting cachix build

### ISSUE THREAD

**Issue by SFrijters** [domenkozar/hie-nix#51]
When I'm trying to build a hie-nix derivation (and not hitting cachix) I'm getting an error building the yaml-0.8.32 package, pretty much hitting this issue: https://github.com/input-output-hk/stack2nix/issues/116.

I ran into this when I changed how I import hie-nix into my `shell.nix`.

Code before (I hit cachix this way and as long as I don't have to build any of the packages myself the derivation works):

```
  hiesJson = builtins.fromJSON ''
    {
      "url": "https://github.com/domenkozar/hie-nix",
      "rev": "6794005f909600679d0b7894d0e7140985920775",
      "date": "2019-02-11T18:14:42+07:00",
      "sha256": "0pc90ns0xcsa6b630d8kkq5zg8yzszbgd7qmnylkqpa0l58zvnpn",
      "fetchSubmodules": false
    }
  '';
  hie-nix = builtins.fetchGit { inherit (hiesJson) url rev; };
  haskell-ide-engine =
    if pkgs.lib.hasPrefix ghcVersion "ghc80" then (import hie-nix {}).hie80 else
    if pkgs.lib.hasPrefix ghcVersion "ghc82" then (import hie-nix {}).hie82 else
    if pkgs.lib.hasPrefix ghcVersion "ghc84" then (import hie-nix {}).hie84 else
                                                  (import hie-nix {}).hie86;
```

Code after (I have to build a long time and then the yaml error breaks the derivation):

```
  hie-nix = pkgs.callPackage (pkgs.fetchFromGitHub {
    # 2019-02-11T18:14:42+07:00
    owner = "domenkozar";
    repo = "hie-nix";
    rev = "6794005f909600679d0b7894d0e7140985920775";
    sha256 = "0pc90ns0xcsa6b630d8kkq5zg8yzszbgd7qmnylkqpa0l58zvnpn";
  }) {};

  haskell-ide-engine =
    if pkgs.lib.hasPrefix ghcVersion "ghc80" then hie-nix.hie80 else
    if pkgs.lib.hasPrefix ghcVersion "ghc82" then hie-nix.hie82 else
    if pkgs.lib.hasPrefix ghcVersion "ghc84" then hie-nix.hie84 else
                                                  hie-nix.hie86;
```

I'm not sure why this change would even change the result of the derivation - sometimes Nix is still a mystery to me - but I should be able to have it build locally anyway, correct?
I'm using a recent pinned nixpkgs that uses yaml-0.11.0, but as far as I could see the yaml-0.8.32 comes from the `ghc-8.6.nix` file in hie-nix?

**Comment by domenkozar** [comment]
What's the store hash of yaml that it's building?

**Comment by SFrijters** [comment]
`/nix/store/8chdq5zlysr4vczbmq9rxzlrnlxvj5yr-yaml-0.8.32.drv`

I think it's pulled in because brittany (`/nix/store/917y625s7lr0hmj3xl4g449wky22k1bb-brittany-0.11.0.0.drv`) has an annoying constraint on yaml.

**Comment by domenkozar** [comment]
Could you try #55?

**Comment by SFrijters** [comment]
Ok, I used the commit from the PR and changed my own nixpkgs pin to match the one in the PR and it seems to work now, apart from the fact that brittany won't build. But that's a nixpkgs issue.
