### ISSUE TITLE
update to HIE 0.7.0.0 + GHC 8.6.4

### ISSUE THREAD

**Issue by mikelpr** [domenkozar/hie-nix#54]

**Comment by domenkozar** [comment]
There's HIE 0.8.0.0 coming out in a few days so I'm waiting for that.

**Comment by ar1a** [comment]
Is there any update on the 8.6.4 issue? hie is basically useless :(

**Comment by domenkozar** [comment]
I've asked in #haskell-ide-engine

**Comment by domenkozar** [comment]
There should be HIE release out in ~2 days.

**Comment by alanz** [comment]
hie 0.8.0.0 is out

**Comment by domenkozar** [comment]
#55
