### ISSUE TITLE
Can't configure cachix on NixOS

### ISSUE THREAD

**Issue by SomeDer** [domenkozar/hie-nix#65]
After running
```
bash <(curl https://nixos.org/nix/install)
```
I get
```
copying Nix to /nix/store..............cp: cannot create directory '/nix/store/./d8wjq00p656k6r9d2dzgsy2pgfcq4f6p-libssh2-1.8.1.26763': Read-only file system
```

**Comment by SomeDer** [comment]
Sorry, didn't notice that it says that this installs nix (which is already installed).

**Comment by domenkozar** [comment]
Interesting, it should say Nix is already installed.

**Comment by SomeDer** [comment]
I think this is a problem with installing nix then, so even if it's an issue, it shouldn't be here.

**Comment by domenkozar** [comment]
Moved to https://github.com/NixOS/nix/issues/2806
